ALTER TABLE `client` CHANGE `foto` `foto` MEDIUMBLOB NULL DEFAULT NULL;
ALTER TABLE `clientverhaal` CHANGE `foto` `foto` MEDIUMBLOB NULL DEFAULT NULL;
ALTER TABLE `medewerker` CHANGE `foto` `foto` MEDIUMBLOB NULL DEFAULT NULL;